### ISSUE TITLE
Pre-release versions of vscode-intelephense being used

### ISSUE THREAD

**Issue by willrowe** [sublimelsp/LSP-intelephense#107]
I was noticing some issues with code that was previously being marked as an error that are no longer being marked in the current version. I tracked it down to a [bug in vscode-intelephense](https://github.com/bmewburn/vscode-intelephense/issues/2939).

Then I noticed that this package had been updated to v1.15.4, which is not a stable version. It is a pre-release version as can be seen [here](https://github.com/bmewburn/vscode-intelephense/releases). Side note: the fact that it is a pre-release is not denoted in the version number itself unfortunately, which makes it very confusing on their end.

Would it be possible to only update this package to use stable versions or to mark any updates to pre-release versions as a pre-release version of this package as well? Having the errors not marked has led to some unfortunate bugs that I usually rely on the LSP to warn me about.

**Comment by jfcherng** [comment]
Version number in ST plugin world is actually quite meaningless. Package Control will just update to whatever the biggest version. It's possible to split a pre-release channel in ST world but I feel it just doesn't worth with a comparison to the maintenance effort.

So I would just revert to the stable version of the server.

---

Plus, I haven't coded in PHP for like probably 3 years so I "probably" won't found ANY issue here. If someone is willing to take over LSP-intelephense, I am welcome.

**Comment by willrowe** [comment]
I'd be glad to help out.

**Comment by jfcherng** [comment]
I have rollback to intelephense v1.10.4 in LSP-intelephense v1.1.12. It should be available within hours.

> I'd be glad to help out.

Does this mean you would like to maintain LSP-intelephense?

**Comment by jfcherng** [comment]
By "maintenance", most of time it's just merging an auto-generated pull request which updates intelephense. And then manually adds a new tag to release a newer version of LSP-intelephense.

**Comment by willrowe** [comment]
Yes, I can do that. I use PHP every day, so this package is something I use a lot.

**Comment by jfcherng** [comment]
> Yes, I can do that. I use PHP every day, so this package is something I use a lot.

I've add you as a maintainer of this repository. Thanks!

**Comment by willrowe** [comment]
Thanks @jfcherng !

**Comment by husanjun** [comment]
IMHO, every version is not perfect, serious bugs will be fixed quickly. In my opinion, the new version solves a lot of problems and has a lot of very good features, which is not worth returning. It would be better if users could customize it.

**Comment by willrowe** [comment]
@husanjun it was pre-release version. Once a stable version has been released, I will update to it.

I do agree that it would be nice to be able to customize which version is installed, but that would probably be better handled at the main LSP package level.

**Comment by husanjun** [comment]
> @husanjun it was pre-release version. Once a stable version has been released, I will update to it.
> 
> I do agree that it would be nice to be able to customize which version is installed, but that would probably be better handled at the main LSP package level.

@willrowe 
I found that sublime supports pre-release  [https://packagecontrol.io/docs/settings#setting-install_prereleases](url)  

  push a tag with pre-release info  Take a look at https://semver.org/

**Comment by willrowe** [comment]
See @jfcherng comment: https://github.com/sublimelsp/LSP-intelephense/issues/107#issuecomment-2239401681
