### ISSUE TITLE
Not indexing .inc files

### ISSUE THREAD

**Issue by nkoporec** [sublimelsp/LSP-intelephense#18]
I'm using Drupal which has certain .inc files in core, I have set up sublime to always open .inc extensions as PHP files but the intelephense is returning functions defined in .inc files as undefined. If I open the .inc file manually then intelephense works as expected.

Is there any way of fixing this? The vscode intelephense extension works correctly, the only settings that I needed to add is the files.associations setting (which is the same as sublime open as setting).

**Comment by jfcherng** [comment]
https://github.com/jfcherng/my-Sublime-Text-settings/blob/2236aa16478dbdeeb8ec6fbdb0c2aebc078c1b74/Packages/User/LSP-intelephense.sublime-settings#L42-L48

This should give you some clue for how to use settings.

**Comment by nkoporec** [comment]
Thanks the "associations" setting worked!

**Comment by frank-bg** [comment]
hi, how did you make it work?

I don't know if I am misunderstanding something, I am on ST3

```
// Settings in here override those in "LSP-intelephense/LSP-intelephense.sublime-settings"

{
	"settings": {
		"files": {
			"associations": [
				// default
				"*.php",
				"*.phtml",
				// my own
				"*.inc",
			],
		}
	}
}
```

**Comment by frank-bg** [comment]
found it, whit the help of #57 using `LSP-json`

```
// Settings in here override those in "LSP-intelephense/LSP-intelephense.sublime-settings"

{
	"settings": {
		"intelephense.files.associations": [
			// default
			"*.php",
			"*.phtml",
			// my own
			"*.inc",
			"*.service",
		],
	}
}
```

**Comment by hanoii** [comment]
I can't figure this out. I am also using Drupal and recently trying LSP-intelephense, I added the settings properly:

```
// Settings in here override those in "LSP-json/LSP-json.sublime-settings"

{
  "settings": {
    "intelephense.format.braces": "k&r",
    "intelephense.files.associations": [
      "*.php",
      "*.phtml",
      // Extra
      "*.inc",
      "*.module",
      "*.install",
      "*.theme",
      "*.profile",
      "*.tpl.php",
      "*.test",
    ],
  },
}
```

But it's not working. It works if I open a `.module` file for instance, the symbols are there, but it doesn't find them globally. It does find symbols globally on php files

**Comment by jfcherng** [comment]
> // Settings in here override those in "LSP-json/LSP-json.sublime-settings"

Are you using those settings for LSP-json?

**Comment by hanoii** [comment]
@jfcherng I don't have LSP-json installed.

**Comment by hanoii** [comment]
I enabled log_debag and log_serber to panel and I see no lsp/intelephense output anywhere until I open a file
