### ISSUE TITLE
Intelephense premium features

### ISSUE THREAD

**Issue by lzaaldian** [sublimelsp/LSP-intelephense#31]
Hello, is this package support the premium features of Intelephense?

If not, do you have any plan to implement premium features in the near future?

**Comment by jfcherng** [comment]
Personally only tried rename. Yes. As for other features, idk.

**Comment by lzaaldian** [comment]
So, it's confirmed that premium features like `Rename`, `Find all implementations` and `Go to xxx` is supported.

I'm curious about how Intelephense premium features could be implemented in Sublime Text? Is it not necessary to enter license to activate premium features like it does in VS Code?

**Comment by jfcherng** [comment]
> I'm curious about how Intelephense premium features could be implemented in Sublime Text? Is it not necessary to enter license to activate premium features like it does in VS Code?

https://github.com/sublimelsp/LSP-intelephense/blob/d7ab5d8d328c0f4001c84d18a23c3c9393f99af8/LSP-intelephense.sublime-settings#L15

**Comment by lzaaldian** [comment]
Thank you for your guidance. I will try it.
