### ISSUE TITLE
Intelephense not working with multiple root folder

### ISSUE THREAD

**Issue by arvx47** [sublimelsp/LSP-intelephense#38]
LPS Intelephense fails detecting project root path when I use multiple folders.

![image](https://user-images.githubusercontent.com/13633641/87717132-ec72b000-c77d-11ea-9f5d-eae92ed489d1.png)

Sublime Text 3, Build 3211

**Comment by jfcherng** [comment]
Could you try to 

1. set `clearCache` to `true` (https://github.com/sublimelsp/LSP-intelephense/blob/2d7260d3e37065b0c0d98fd974cb27571d929224/LSP-intelephense.sublime-settings#L16)
1. restart ST 
1. wait for intelephense to finish indexing
1. see if the issue persists

**Comment by ariel0196** [comment]
Hi @jfcherng, thank you for answering. 

Already tried those methods but none seems to be working:

1. Tried setting **clearCache** to true and restarting sublime text (also restarting LSP servers on command palette)
![image](https://user-images.githubusercontent.com/13633641/87748643-75143f00-c7c4-11ea-9f63-c16538f35a6a.png)

2. Having those files living in my currently project folder "**C:/laragon/www/api.subastas/**", tried defining their paths in both Intelphense Settings "**intelephense.environment.includePaths**" and "**intelephense.environment.documentRoot**" as you mentioned, but there was no luck.
![image](https://user-images.githubusercontent.com/13633641/87749764-93c80500-c7c7-11ea-9528-6404fe2f0136.png)

With only one root folder works like a charm

![image](https://user-images.githubusercontent.com/13633641/87749985-2ec0df00-c7c8-11ea-9dc1-01b161e9d6ce.png)

**Comment by jfcherng** [comment]
> Having those files living in my current project folder "C:/laragon/www/api.subastas/", tried defining their paths in both Intelphense Settings "intelephense.environment.includePaths" and "intelephense.environment.documentRoot" as you mentioned, but there was no luck.


Settings should be in `settings` like https://github.com/sublimelsp/LSP-intelephense/blob/2d7260d3e37065b0c0d98fd974cb27571d929224/LSP-intelephense.sublime-settings#L22-L29

```js
"settings": {
  "intelephense": {
    "environment": {
      "includePaths": [
        // ...
      ],
    },
  },
},
```

**Comment by ariel0196** [comment]
Oops, I am sorry! I misread the config structure.

So fixing it made it works!

![image](https://user-images.githubusercontent.com/13633641/87801871-60fd2b80-c81e-11ea-818b-8cd81a3e3a80.png)

I also realised that Itelephense is reindexing the files thrice if I use `includePaths: ["C:\\laragon\\www\\api.subastas"] `, but if I use `includePaths: ["."]` it only reindexes twice, but still works

![image](https://user-images.githubusercontent.com/13633641/87807705-986fd600-c826-11ea-9d9b-3328739edaaf.png)

So ending up I cant get my head around why these configs must be setted in order to get things working and why the first reindexes thrice.

---
> By the way, how you guys edit LSP-* settings. I assume it should be auto opened in a side-by-side view, which makes the editing straightforward but I've seen some people like manually open the settings file from OS file explorer.

Yes, they are opened in a side-by-side view. But I missread it because that part of `{ settings: { intelephense: { settings: {}  } }` got little bit trickier for me 😅

**Comment by jfcherng** [comment]
> I also realised that Itelephense is reindexing the files thrice if I use `includePaths: ["C:\\laragon\\www\\api.subastas"] `, but if I use `includePaths: ["."]` it only reindexes twice, but still works

So basing on your experiments, it works for both relative and absolute paths, right?

**Comment by rwols** [comment]
In ST4, you can also use the $folder template to refer to the *first* folder to make it somewhat portable.

**Comment by jfcherng** [comment]
> In ST4, you can also use the $folder template to refer to the _first_ folder to make it somewhat portable.

But there could be many root dirs in a workspace.

**Comment by ariel0196** [comment]
> So basing on your experiments, it works for both relative and absolute paths, right?
> I am wondering how relative settings work. A global relative path doesn't make sense but one in per-project settings does.

Yes, it works for both relative and absolute paths. 

> Relative path in per-project settings should be useful since absolute settings is not portable.

Exactly, thats what I am going to do with my projects since now.

Thank you so much for your help!

**Comment by jfcherng** [comment]
Closed because the problem had seemed to be solved.
