### ISSUE TITLE
Index activity indicators do not disappear

### ISSUE THREAD

**Issue by husanjun** [sublimelsp/LSP-intelephense#53]
when I switch project，In the current view the index activity indicator increases but does not disappear

**Comment by rchl** [comment]
Try to restart ST and make sure that all dependencies are up to date (specificially `lsp_utils`).

**Comment by husanjun** [comment]
Sorry, I didn't make myself clear.
It is usually fine, but when editing Settings or switching project in succession, multiple indicators appear and do not disappear,  the last state is not removed
![image](https://user-images.githubusercontent.com/49985266/102157281-2aedd180-3eba-11eb-9108-a8de43758923.png)

**Comment by rchl** [comment]
I think #54 should fix it.

**Comment by predragnikolic** [comment]
Wasn't this issue fixed with https://github.com/sublimelsp/lsp_utils/pull/49 ?

**Comment by rchl** [comment]
Should be fixed with https://github.com/sublimelsp/lsp_utils/pull/50

Or I hope so at least.

> Wasn't this issue fixed with [sublimelsp/lsp_utils#49](https://github.com/sublimelsp/lsp_utils/pull/49) ?

Sounds like those are separate issues.
I think this issue could happen if we destroy the server before it had a chance to stop the status hence the extra fix.
