### ISSUE TITLE
Somehow ending up with duplicate definitions in tooltips

### ISSUE THREAD

**Issue by Xuerian** [sublimelsp/LSP-intelephense#55]
When I load a file or restart ST, I mouseover and I get one definition: 

![image](https://user-images.githubusercontent.com/2985/102408507-ac795880-3fbb-11eb-8ff4-a464c03a64cb.png)

When I make a change, I see the original and the current:

![image](https://user-images.githubusercontent.com/2985/102408607-da5e9d00-3fbb-11eb-8ee4-79038c09a05e.png)

I'm not sure where the issue is, LSP, LSP-intelephense, or Intelephense, so I'm starting here and would be glad for help with figuring that out. I don't seem to have the same issue in VSCode with that Intelephense extension.

This seems to be reflected in more than just tooltips, but this was the easiest way to show it.

**Comment by rchl** [comment]
That content is controlled by the server (intelephense in this case).

If you can log the server communication then that would make it clear.

 - In LSP settings add:
```
log_server: true,
log_payloads: true,
```
- restart ST
- from the command palette run `LSP: Toggle Log Panel`

**Comment by Xuerian** [comment]
After making the change shown (or any similar change) in the above images, the hover request does return two definitions, one from the initial index and the other the current, if it's different.

I can't really understand why that would be the case, if VSCode's version doesn't have a similar problem on the same project.

A configuration difference on my part?

**Comment by rchl** [comment]
Can you try to close all file tabs then open just this single file and try to reproduce?

**Comment by Xuerian** [comment]
I closed all file tabs, closed sublime, reopened, and opened a single tab of that file and experienced the same thing.

**Comment by rchl** [comment]
OK then. You should enable logging as mentioned in https://github.com/sublimelsp/LSP-intelephense/issues/55#issuecomment-747344900 and provide a full log from the LSP log panel from the time since you've started LSP up to the point when you reproduce the issue.

It should be clear from the log if we are doing something wrong with normalizing the file path.

**Comment by Xuerian** [comment]
Using Go to Symbol Definition on:
```
<?php


/** @return bool */
function a(): bool
{
	return true;
}

```
:: --> lsp-intelephense initialize(1): {'rootUri': 'file:///C:/Users/------/deploy', 'rootPath': 'C:\\Users\\------\\deploy', 'capabilities': {'window': {'showMessage': {'messageActionItem': {'additionalPropertiesSupport': True}}, 'workDoneProgress': True}, 'experimental': {}, 'textDocument': {'implementation': {'dynamicRegistration': True, 'linkSupport': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}, 'dynamicRegistration': True}, 'rename': {'dynamicRegistration': True}, 'formatting': {'dynamicRegistration': True}, 'signatureHelp': {'signatureInformation': {'documentationFormat': ['markdown', 'plaintext'], 'parameterInformation': {'labelOffsetSupport': True}}, 'dynamicRegistration': True}, 'rangeFormatting': {'dynamicRegistration': True}, 'references': {'dynamicRegistration': True}, 'publishDiagnostics': {'relatedInformation': True}, 'definition': {'dynamicRegistration': True, 'linkSupport': True}, 'typeDefinition': {'dynamicRegistration': True, 'linkSupport': True}, 'colorProvider': {'dynamicRegistration': True}, 'documentHighlight': {'dynamicRegistration': True}, 'documentSymbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'hierarchicalDocumentSymbolSupport': True, 'dynamicRegistration': True}, 'completion': {'completionItem': {'snippetSupport': True}, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, 'dynamicRegistration': True}, 'synchronization': {'didSave': True, 'willSaveWaitUntil': True, 'willSave': True, 'dynamicRegistration': True}, 'hover': {'contentFormat': ['markdown', 'plaintext'], 'dynamicRegistration': True}, 'declaration': {'dynamicRegistration': True, 'linkSupport': True}}, 'workspace': {'applyEdit': True, 'didChangeConfiguration': {'dynamicRegistration': True}, 'configuration': True, 'executeCommand': {}, 'workspaceEdit': {'failureHandling': 'abort', 'documentChanges': True}, 'symbol': {'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, 'dynamicRegistration': True}, 'workspaceFolders': True}}, 'processId': 5084, 'clientInfo': {'version': '0.14.3', 'name': 'Sublime Text LSP'}, 'initializationOptions': {'clearCache': True}, 'workspaceFolders': [{'uri': 'file:///C:/Users/------/deploy', 'name': 'deploy'}]}
lsp-intelephense: Initialising intelephense 1.5.4
lsp-intelephense: Initialised in 18 ms
:: <<< lsp-intelephense 1: {'capabilities': {'codeActionProvider': False, 'completionProvider': {'triggerCharacters': ['$', '>', ':', '\\', '/', '*', '.', '<'], 'resolveProvider': True}, 'documentSymbolProvider': True, 'referencesProvider': True, 'declarationProvider': False, 'renameProvider': False, 'workspaceSymbolProvider': True, 'selectionRangeProvider': False, 'signatureHelpProvider': {'triggerCharacters': ['(', ',']}, 'hoverProvider': True, 'documentRangeFormattingProvider': False, 'definitionProvider': True, 'documentHighlightProvider': True, 'textDocumentSync': 2, 'typeDefinitionProvider': False, 'foldingRangeProvider': False, 'implementationProvider': False, 'documentFormattingProvider': False, 'workspace': {'workspaceFolders': {'supported': True, 'changeNotifications': True}}}}
::  -> lsp-intelephense initialized: {}
::  -> lsp-intelephense textDocument/didOpen
:: <-- lsp-intelephense client/registerCapability(0): {'registrations': [{'method': 'workspace/didChangeWorkspaceFolders', 'id': '14b375a6-bcba-4d20-b00b-8b94e0f55e09', 'registerOptions': {}}]}
:: >>> lsp-intelephense 0: None
:: <-- lsp-intelephense workspace/configuration(1): {'items': [{'section': 'intelephense'}, {'scopeUri': 'file:///C:/Users/------/deploy', 'section': 'intelephense'}]}
:: >>> lsp-intelephense 1: [None, None]
:: <-- lsp-intelephense client/registerCapability(2): {'registrations': [{'method': 'textDocument/formatting', 'id': '21115d4f-b1d7-46aa-be99-f5c8756e8940', 'registerOptions': {'documentSelector': [{'scheme': 'file', 'language': 'php'}, {'scheme': 'untitled', 'language': 'php'}]}}, {'method': 'textDocument/rangeFormatting', 'id': '52d11686-6432-47ab-8086-79e793457c43', 'registerOptions': {'documentSelector': [{'scheme': 'file', 'language': 'php'}, {'scheme': 'untitled', 'language': 'php'}]}}]}
:: >>> lsp-intelephense 2: None
:: <-- lsp-intelephense client/registerCapability(3): {'registrations': [{'method': 'workspace/didChangeConfiguration', 'id': '6fe700a4-86f1-4518-89fb-6d536b3e6d05', 'registerOptions': {'section': 'intelephense'}}]}
:: >>> lsp-intelephense 3: None
lsp-intelephense: Indexing started.
:: <-  lsp-intelephense indexingStarted: None
:: <-  lsp-intelephense textDocument/publishDiagnostics: {'uri': 'file:///C:/Users/------/deploy/source/lsp-test.php', 'diagnostics': []}
lsp-intelephense: Indexing ended. 303 files indexed in 1s.
lsp-intelephense: Writing state to C:\Users\-----\AppData\Local\Temp\intelephense\7d771254.
:: <-  lsp-intelephense indexingEnded: None
lsp-intelephense: Wrote state in 0.3s.
:: <-  lsp-intelephense textDocument/publishDiagnostics: {'uri': 'file:///C:/Users/------/deploy/source/lsp-test.php', 'diagnostics': []}
:: --> lsp-intelephense textDocument/definition(2): {'position': {'line': 4, 'character': 10}, 'textDocument': {'uri': 'file:///C:/Users/------/deploy/source/lsp-test.php'}}
:: <<< lsp-intelephense 2: [{'targetRange': {'start': {'line': 4, 'character': 0}, 'end': {'line': 7, 'character': 1}}, 'targetUri': 'file:///C:/Users/------/deploy/source/lsp-test.php', 'originSelectionRange': {'start': {'line': 4, 'character': 9}, 'end': {'line': 4, 'character': 10}}, 'targetSelectionRange': {'start': {'line': 4, 'character': 9}, 'end': {'line': 4, 'character': 10}}}, {'targetRange': {'start': {'line': 4, 'character': 0}, 'end': {'line': 7, 'character': 1}}, 'targetUri': 'file:///c%3A/Users/------/deploy/source/lsp-test.php', 'originSelectionRange': {'start': {'line': 4, 'character': 9}, 'end': {'line': 4, 'character': 10}}, 'targetSelectionRange': {'start': {'line': 4, 'character': 9}, 'end': {'line': 4, 'character': 10}}}]
:: --> lsp-intelephense textDocument/documentHighlight(3): {'position': {'line': 4, 'character': 9}, 'textDocument': {'uri': 'file:///C:/Users/------/deploy/source/lsp-test.php'}}
:: <<< lsp-intelephense 3: [{'range': {'start': {'line': 4, 'character': 9}, 'end': {'line': 4, 'character': 10}}, 'kind': 2}]
 
```


There's a wonky targetUri in that reply

**Comment by rchl** [comment]
It does look like a server issue since we've only notified it about a `file:///C:/Users/...` file but it internally seems to be seeing two versions of this file. One with `file:///C:/Users/...` and one with `file:///c%3A/Users/...` path.

It might work in VSCode because VSCode normalizes and encodes drive letters in the path but since this is not required per spec, I think the server needs to make sure that it normalizes and dedupes paths.

CC @bmewburn

(BTW. in your log the params sent to `textDocument/didOpen` seem missing but I'm assuming we've sent `file:///C:/Users/` since that's what we're sending everywhere else).

**Comment by Xuerian** [comment]
ST4 seems to be the same.

**Comment by bmewburn** [comment]
Thanks @rchl , I've opened https://github.com/bmewburn/vscode-intelephense/issues/1555

**Comment by husanjun** [comment]
The  same problem sublimelsp/LSP#1526

**Comment by willrowe** [comment]
This appears to have been fixed upstream. Please re-open if it is still an issue though.
