### ISSUE TITLE
Is textDocument/definition supposed to work on require_once?

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-intelephense#58]
I don't know much about PHP but I have to use it for my job sometimes. There are some PHP files which contain a require_once line, something like `require_once('foo/bar/baz.php')`.

Similarly in C++ you can write `#include "foo/bar/baz.hpp"`. clangd, a language server for C++ files, allows me to "goto definition" on that line, and it opens the included file. Is this also supposed to work like this in intelephense? If not I might open an issue about it on the intelephense repo.

**Comment by jfcherng** [comment]
I don't think `intelephense` has that feature at this moment but it definitely can be a plus.

**Comment by willrowe** [comment]
This has not been implemented upstream, but there is [a request for it](https://github.com/bmewburn/vscode-intelephense/issues/338).

I'm closing this since it should work if ever implemented upstream.
