### ISSUE TITLE
The problem of  ActivityIndicator 

### ISSUE THREAD

**Issue by husanjun** [sublimelsp/LSP-intelephense#59]
Hi @rchl , In some special cases, such as adding/removing folders to a project continuously, the #53  still exists
https://github.com/sublimelsp/LSP-intelephense/blob/6984329e50f2071bfb9dc236dea718fe9090720b/plugin.py#L2

However, the problem went away after I used `sublime_lib`, so whether we should replace the current dependency
https://github.com/sublimelsp/LSP-intelephense/blob/59a966f483b9751a190f55d019e2d322116c9f49/plugin.py#L4

@jfcherng  what do you think

**Comment by husanjun** [comment]
BTW, Many improvements and fixes were made after the problem https://github.com/sublimelsp/LSP-pyright/issues/36

**Comment by rchl** [comment]
Ideally it would also support the `set_label` method like in our fork:
https://github.com/sublimelsp/lsp_utils/blob/872cc0e3384c216bda52c3fb3e9d8706975940da/st3/lsp_utils/activity_indicator.py#L109-L117

Although to do it in a thread-safe way, it would need to be a bit more complex.

**Comment by jfcherng** [comment]
Will `ActivityIndicator` from `lsp_utils` be deprecated? If not, I suppose it should be fixed in `lsp_utils`?

**Comment by rchl** [comment]
Ideally it should be deprecated since sublime_lib made it run on main thread also.

**Comment by jfcherng** [comment]
@husanjun Could you manually try the latest commit? If it fixes the problem, let's do a new release.

**Comment by husanjun** [comment]
> @husanjun Could you manually try the latest commit? If it fixes the problem, let's do a new release.

Sorry, my computer is not with me, if you can, I will give you feedback tomorrow

**Comment by husanjun** [comment]
Hello @jfcherng , My tests work fine. In addition, I submitted a PR https://github.com/sublimelsp/LSP-intelephense/pull/61
