### ISSUE TITLE
Compiled extensions

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-intelephense#65]
At work there are quite a bit of compiled extensions. Intelephense does not provide completions for these extensions. How can I make intelephense understand compiled extensions?

**Comment by jfcherng** [comment]
https://github.com/bmewburn/vscode-intelephense/blob/bd8bd154dddfb117b62f61bdbd825cd6629b7a35/package.json#L147

**Comment by husanjun** [comment]
You can also include your own extensions  https://github.com/bmewburn/vscode-intelephense/issues/1754

**Comment by jfcherng** [comment]
I assume this has been resolved?

**Comment by rwols** [comment]
Yes
