### ISSUE TITLE
global name 'path' is not defined

### ISSUE THREAD

**Issue by anovsiradj** [sublimelsp/LSP-intelephense#66]
hello.

in the last few days, the package keep complaining about `global name 'path' is not defined`.
i am not pretty sure how this happen.

![image](https://user-images.githubusercontent.com/6737021/122661299-e0277c00-d1b2-11eb-8918-8645818c133a.png)

sublime console
```sh
Unable to start subprocess for LSP-intelephense
Traceback (most recent call last):
  File "C:\Users\JMC002\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 324, in start_async
    cwd = plugin_class.on_pre_start(self._window, initiating_view, workspace_folders, config)
  File "C:\Users\JMC002\AppData\Roaming\SUBLIM~1\Packages\LSP_UT~1\st3\lsp_utils\_client_handler\abstract_plugin.py", line 130, in on_pre_start
    extra_paths = path.pathsep.join(cls.get_additional_paths())
NameError: global name 'path' is not defined
```

*(sorry forr my english)*

**Comment by anovsiradj** [comment]
apparently, my `lsp_utils` folder is not update.

uninstall then re-install the `LSP-intelephense` will delete and re-create `lsp_utils` folder.
(but re-installing `LSP` package will not).

**Comment by rchl** [comment]
In case anyone stumbles upon this issue, the solution is to run `Package Control: Satisfy Dependencies` from the Command Palette.
