### ISSUE TITLE
Error enabling LSP-intelephense

### ISSUE THREAD

**Issue by DerrikMilligan** [sublimelsp/LSP-intelephense#67]
Heyo, thanks for this port first of all! It's fantastic when it's working.

I'm running Linux Mint 20 with Sublime Text version 4107

But after having ran it for several days with no issues, now whenever I try and enable it with I get the error `global name 'path' is not defined`. I've attempting to google around for this error with just intelephense on it's own and haven't been able to find anything. I think it's related to this extension. I thought to open the consoles and see this output:
```
Unable to start subprocess for LSP-intelephense
Traceback (most recent call last):
  File "/home/zzz/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 324, in start_async
    cwd = plugin_class.on_pre_start(self._window, initiating_view, workspace_folders, config)
  File "/home/zzz/.config/sublime-text-3/Packages/lsp_utils/st3/lsp_utils/_client_handler/abstract_plugin.py", line 130, in on_pre_start
    workspace_folders: List[WorkspaceFolder], configuration: ClientConfig) -> Optional[str]:
NameError: global name 'path' is not defined
```

Not sure what I did or changed for this to start happening, but any help would be greatly appreciated.

**Comment by rwols** [comment]
Run “Package Control: Satisfy Dependencies” from the command palette.

**Comment by rwols** [comment]
The bug originates from lsp_utils. The faulty version was the most recent one for just ~6 hours, after which it was fixed. This happened about a week ago. I’m wondering why package control isn’t updating dependencies. https://github.com/sublimelsp/lsp_utils/releases

**Comment by DerrikMilligan** [comment]
Thanks man. It seems to be working after manually updating everything and getting their dependencies satisfies. Sorry for posting the problem here haha.
