### ISSUE TITLE
Does not start automatically on Sublime 4

### ISSUE THREAD

**Issue by davidwebca** [sublimelsp/LSP-intelephense#68]
In the early versions of Sublime 4, LSP-intelephense would start automatically when I booted up my project, but now I can't find a way to restart it / enable it and it does not automatically, since a few updates of Sublime 4 ago.

Also, LSP-intelephense is not showing in the "Enable language server globally" and the only way I found to force it's reinitialization is to open the settings files and save it. I don't know what it's trigerring but I'd love to find a way to make it work again.

**Comment by jfcherng** [comment]
Could you provide your project settings?

Via `Project` -> `Edit Settings`

**Comment by davidwebca** [comment]
The only tidbit I have in there is to customize the root font-size of lsp-tailwindcss, but I tested removing the whole part about lsp and it doesn't work. 

```json
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings": {
		"LSP": {
			"LSP-tailwindcss": {
				"settings": {
					"tailwindCSS.rootFontSize": 24
				}
			}
		}
	}
}
```

When I hit "Enable Language Server Globally", I get those suggestions even though the languages that I have are those below, but I don't know if it's related.
<img width="611" alt="Capture d’écran, le 2021-07-16 à 07 21 42" src="https://user-images.githubusercontent.com/412352/125940248-0b30bc17-5326-4521-8954-c3ce1875f9aa.png">

<img width="427" alt="Capture d’écran, le 2021-07-16 à 07 22 03" src="https://user-images.githubusercontent.com/412352/125940285-b4fd6806-1906-4010-b02a-0ac0576d8084.png">

**Comment by jfcherng** [comment]
Is there anything related to LSP-intelephense in the diagnostics panel?
![image](https://user-images.githubusercontent.com/6594915/125940959-b0098e01-bcee-4d4c-a054-a0a1695ed102.png)

**Comment by davidwebca** [comment]
When I boot Sublime, nothing shows in the diagnostics or log panel. When I save the settings files, everything works fine and logs the initialization sequence, does not complain about anything in the diagnostics either. I realized intelephense does show up in the "Enable Language Server In Project" menu though, but disabling and re-enabling it does nothing as long as I haven't forced its initialization. 

Could it be an issue with LSP not booting up early enough and so it would not restart the previous servers automatically?

**Comment by jfcherng** [comment]
Does it happen in every project?

**Comment by davidwebca** [comment]
Yup. Other servers boot normally if they're enabled in the project.

**Comment by jfcherng** [comment]
I have no clue at this moment...

**Comment by davidwebca** [comment]
No worries, thanks a lot for replying fast. I'll see if I can dig up something more precise and I'll report back.

**Comment by husanjun** [comment]
If there is a video, it may be easier to find the problem

**Comment by davidwebca** [comment]
Since the latest Sublime 4 updates, it seems to have been fixed. It might have been a compatibility issue with PHP versions too, but I'm not quite sure. I'll close the issue and reopen if need be. For now all is good and I've been using it properly for a while!
