### ISSUE TITLE
Index not working on workspace

### ISSUE THREAD

**Issue by franck-paul** [sublimelsp/LSP-intelephense#71]
I have a workspace with two folders:

project > folder1 and project > folder2

These two folders were added in a new project.

Some PHP source in folder2 use classes and methods defined in folder1 but intelephense says that these classes/methods are unknonw.

Why ?

Is there any option to have an index on the **entire** project (ie all sources in every folders added to the project)?

ST is able to give references all other the workspace but using LSP-intelephense remove the ST reference popup and replace it by its own, so I don't know how to fix this.

**Comment by franck-paul** [comment]
Note that I have the _premium_ version of intelephense.

**Comment by jfcherng** [comment]
https://github.com/bmewburn/vscode-intelephense/issues/1799

**Comment by franck-paul** [comment]
Thanks for the clue!

I add the folders to the LSP-intelephense settings and everything seems to be ok. Do you know if it is possible to set this settings only for one projet? May be in the sublime-project file?

**Comment by jfcherng** [comment]
> May be in the sublime-project file?

```js
{
    "folders":
    [
        // ...
    ],
    "settings": {
        "LSP": {
            "LSP-intelephense": {
                "settings": {
                    "intelephense.environment.includePaths": [
                        // ...
                    ]
                }
            }
        }
    }
}
```

**Comment by franck-paul** [comment]
I will try, thanks

**Comment by willrowe** [comment]
Closing this since a solution was found.
