### ISSUE TITLE
licence key file created in each indexed folder

### ISSUE THREAD

**Issue by franck-paul** [sublimelsp/LSP-intelephense#74]
I put `"$licenceKey": "${packages}/User/intelephense-license.txt"`  as setting (in `"initializationOptions": {…}` ) but LSP-intelephense still create a folder `~\.intelephense\intelephense_license_key_XXXX` in each indexed folder as soon as open a PHP file in them.

Is there any option to avoid this behavior?

PS: The intelephense-license.txt has been created in `${packages}/User` folder and contains my license key.

**Comment by jfcherng** [comment]
This should be an issue for the server, `intelephense`.

**Comment by franck-paul** [comment]
But I also set stores:

```json
	"initializationOptions": {
		"licenceKey": "${packages}/User/intelephense-license.txt",
		"storagePath": "/tmp/intelephense",
		"globalStoragePath": "~/.intelephense",
	},
```
