### ISSUE TITLE
How to enable formatting check?

### ISSUE THREAD

**Issue by rusproject** [sublimelsp/LSP-intelephense#80]
Intelephense doesn't show any formatting issues, although as I can see at https://github.com/bmewburn/vscode-intelephense/blob/master/package.json, formatting is set to PSR-12 and enabled by default.
I've tried to explicitly add this settings but that doesn't work:

![image](https://user-images.githubusercontent.com/62891105/210417239-e65a65da-580b-4b41-9df1-cfc97be6c679.png)

How can I enable formatting check so I can see if any of my code is not comply with PSR-12?

**Comment by jfcherng** [comment]
I don't think it provides any style check. `intelephense.format.braces` is for the braces style when running formatting with intelephense. TBH, either style check or formatting, intelephense is an inferior solution.

There are plenty of solutions, especially for style check. I use php-cs-fixer if you ask.

**Comment by rusproject** [comment]
Thanks for the clarification, I will look for some codestyle plugin, though intelephense has this feature built-in.

About your last sentence, what do you mean by "if Intelephense doesn't format your code ..."? What code and when (or how) can be formatted by the Intelephense?

**Comment by jfcherng** [comment]
> About your last sentence, what do you mean by "... Intelephense doesn't format your code ..."? What code and when (or how) can be formatted by the Intelephense?

before:

```php
final
class
Combined
extends
AbstractHtml {}
```

after:

```php
final
class
Combined
extends
AbstractHtml
{
}
```

So, I just don't use it for formatting while php-cs-fixer is pretty mature as of PHP5 era.

**Comment by rusproject** [comment]
Oh I'm sorry, now I can see that LSP-intelephense has "Format file" command, which is really fixes some issues.
Yeah it isn't perfect, and doesn't actually solve the problem:
I would like to have a tool which will highlight formatting issues (just like SublimeLinter+ESlint does for .js files for example), not fixing issues itself (like intelephense or php-cs-fixer).

Can't find any working solution as for now. Any clue what tool or plugin for ST could I use?

**Comment by rchl** [comment]
I'm not into php ecosystem but I would suggest trying to find some existing tool that does decent linting of php. If it exists then there should exist one way or another to run it as LSP (or SublimeLinter).

**Comment by jfcherng** [comment]
Yes, for example, https://packagecontrol.io/packages/SublimeLinter-phpcs. I am sure PHP_CodeSniffer can check for PSR-12 but you may need to find how to properly configure it with SublimeLinter-phpcs. And if you prefer the LSP diagnostic panel, use https://github.com/iamcco/diagnostic-languageserver along with PHP_CodeSniffer should probably a way to go too.

**Comment by rusproject** [comment]
@jfcherng Thank you, phpcs + sublimeLinter seems to work.

![image](https://user-images.githubusercontent.com/62891105/210831498-c0673e81-ec30-45fb-8acc-02368bc1e77b.png)


Now trying to figure out how to control rules, because I don't actually need "tabs instead of spaces" error and some other.

**Comment by willrowe** [comment]
Closing this since some solutions were discussed and no issues with this package were identified.
