### ISSUE TITLE
"generate docblock" quick action not working anymore

### ISSUE THREAD

**Issue by vazaha-nl** [sublimelsp/LSP-intelephense#83]
I am not sure whether this is an issue with this sublime plugin, or maybe with intelephense itself. But I used to see a "quick fix" code action "generate docblock" when I hover over a (class) function. It is not there anymore, since some time (not sure how long). 

For the rest Intelephense is working like it should. I do see other quick code actions, like import symbol when hovering over a class name without import statement. 

I am using the licensed version of intelephense (latest version). Plugin version 1.0.30, Sublime Text build 4143.

Anyone else experiencing the same issue?

**Comment by jfcherng** [comment]
I can see 
![image](https://user-images.githubusercontent.com/6594915/214601273-8792ba89-ae0a-45cb-8e26-f67806b21b47.png)
when I trigger code action manually. But honestly, I would recommend DoxyGen plugin.

**Comment by vazaha-nl** [comment]
@jfcherng hmm yes I see that too. So the functionality still works, that's great. Question remains, why did the shortcut disappear, is there a way to bring it back? I liked to use it a lot. Manual trigger is extra work.

I have also used DoxyDoxyGen but as you say intelephense is more intelligent.

**Comment by jfcherng** [comment]
Not related to LSP-intelephense anyway. Should be a LSP question.

**Comment by willrowe** [comment]
Closing this since it is related to the main LSP package and not this one.
