### ISSUE TITLE
Laravel ide helper support 

### ISSUE THREAD

**Issue by zigi05** [sublimelsp/LSP-intelephense#84]
[Laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) not working on Sublime Text 4 with lsp-intelephense installed.

**Comment by jfcherng** [comment]
restart ST? This won't be an issue of LSP-intelephense anyway.

**Comment by zigi05** [comment]
I'm trying to use the helper for facades, but they still don't autocomplete or recognized without error.
![image](https://user-images.githubusercontent.com/10746393/214849651-b5fb353a-b9e7-410a-95d6-0c63f34d7ebb.png)

**Comment by jfcherng** [comment]
v1.0.31 has been released. That may fix this.

**Comment by zigi05** [comment]
@jfcherng not working :(
![image](https://user-images.githubusercontent.com/10746393/218774578-748b0b4d-76de-46bd-b233-77e32a131acb.png)

**Comment by jfcherng** [comment]
What's the error msg?

**Comment by zigi05** [comment]
[laravel-ide-helper](https://github.com/barryvdh/laravel-ide-helper) helps code autocompletion service (in our case lsp-intelephense) discover laravel global facades to enable autocompletion. So in ST4 with LSP-Intelephense the laravel-ide-helper has no effect, the `Route` facade, for example, is not discover, not autocompleted. Here's the error it has:
![image](https://user-images.githubusercontent.com/10746393/218782644-ff1f6d12-2573-4ce1-a381-f5b9770063ec.png)

**Comment by jfcherng** [comment]
Can you try to delete intelephense's cache directory? It's in your home directory with name `.intelephense`.

**Comment by jfcherng** [comment]
If the issue persists, I suggest you go to the issue link I post since we can't help here.

**Comment by zigi05** [comment]
> Can you try to delete intelephense's cache directory? It's in your home directory with name `.intelephense`.

This helped. Thank you.
