### ISSUE TITLE
rename with global variables issue

### ISSUE THREAD

**Issue by 8ctopus** [sublimelsp/LSP-intelephense#86]
As an example, rename from `$mail` to `$_ENV['MAIL']` does not work.
Sublime Text 4143 on Windows.

**Comment by jfcherng** [comment]
We don't implement the function but just follow what the server instructs. That says, this is an upstream issue. If you are interested in it, please file it to https://github.com/bmewburn/vscode-intelephense.

**Comment by 8ctopus** [comment]
Thank you, I've reported the issue upstream.
