### ISSUE TITLE
PHP tag formatted wrong inside HTML script tags

### ISSUE THREAD

**Issue by todordvv** [sublimelsp/LSP-intelephense#87]
When I try to inject a PHP variable inside inline JS code (inside a <script> block) the code formatter formats this:

![image](https://user-images.githubusercontent.com/125922567/225070208-b82f2da3-1c2d-49dd-8c95-736af6a7020e.png)

As such:

![image](https://user-images.githubusercontent.com/125922567/225070272-24c123ff-9129-4f17-8fb8-78447e090820.png)

i.e. it adds a space betweeh the "<?" and the "php" of the open php tag - which results in a JS error. This does not happen if the whole PHP block is wrapped in quotes (treated as string):

![image](https://user-images.githubusercontent.com/125922567/225070589-1134e4ec-b0bb-4473-b1dc-5ee81717c9ce.png)

Code to test with (test.php file):

```
<div>
	<?php $accordion_count = 10; ?>
</div>
<script>
	window.accordion_count = <?php echo $accordion_count; ?>;
	window.accordion_count = "<?php echo $accordion_count; ?>";
	window.accordion_count = parseInt("<?php echo $accordion_count; ?>");
</script>
```

If you try to format this code you will notice the issue in the first of the three JS variable lines.

**Comment by jfcherng** [comment]
Confirmed but we don't implement the function but just follow what the server instructs. That says, this is an upstream issue or feature request. If you are interested in it, please file it to [bmewburn/vscode-intelephense](https://github.com/bmewburn/vscode-intelephense).

Btw, if it works in VSCode but not in ST, then it's most likely our issue.
