### ISSUE TITLE
Template format

### ISSUE THREAD

**Issue by pacoVela** [sublimelsp/LSP-intelephense#92]
Using LSP-json I obtain a default template for function phpdoc:
```
    "intelephense.phpdoc.functionTemplate": {
          "summary": "${1:$SYMBOL_NAME}",
	         "tags": [
		        "@param ${1:$SYMBOL_TYPE} $SYMBOL_NAME $2",
			"@return ${1:$SYMBOL_TYPE} $2",
			"@throws ${1:$SYMBOL_TYPE} $2"
		]
	}
```

But I obtain this: 
```
    /**
     * @param   
     * @return  
     */
    private function getPagePoolFeaturesAsArrayOfSlugs(array $page)
```

I've tried both "text" and "snippet" in the  "intelephense.phpdoc.textFormat" option.

But if i delete my config it works like that:
```
    /**
     * @param array $page 
     * @return array 
     */
    private function getPagePoolFeaturesAsArrayOfSlugs(array $page)
```
So I think that the problem is the format of the template. How could I get the correct format to use?

**Comment by jfcherng** [comment]
Doesn't seem to work indeed. Since the server is not open source, I guess you can only ask the author on https://github.com/bmewburn/vscode-intelephense/issues

**Comment by pacoVela** [comment]
Thank you, it works!

**Comment by rchl** [comment]
We should update the package schema so that the default example is properly escaped.
