### ISSUE TITLE
Show info about uncaught exceptions

### ISSUE THREAD

**Issue by fadrian06** [sublimelsp/LSP-intelephense#95]
Someone tell me if there is ever support for Info messages about **uncaught exceptions** thanks to the _@throws_ tag in the docblock. Similar to the Info message about the _@deprecated_ tag🙌🏽🙌🏽🙌🏽

When I took a java course with _lsp-jdtls_ I noticed that when I don't handle possible exceptions it gives me an info, even a quickFix to group the code in a `try/catch`.

It would be great to have the same functionality in php

**Comment by jfcherng** [comment]
![image](https://github.com/sublimelsp/LSP-intelephense/assets/6594915/2572ad92-0c01-453a-9c16-6f0a6871aef1)

**Comment by jfcherng** [comment]
Nonetheless, if the features you requested is not there, nothing we can do here. You should file an feature request to the server's repository instead.

**Comment by jfcherng** [comment]
No. There doesn't seem to be info about "uncaught exceptions" from my experiments.

```php
<?php

/**
 * This is foo.
 *
 * @deprecated don't use this function
 *
 * @throws     JsonException
 * @throws     RuntimeException
 */
function foo()
{
    $rand = rand(0, 100);

    if ($rand > 50) {
        throw new RuntimeException('A');
    } else {
        throw new JsonException('B');
    }
}


try {
    foo();
} catch (Throwable $e) {
    echo 'Throwable: ' . $e->getMessage();
}
```

But at the same time, I may not want to caught them here but at a more upper level.

**Comment by jfcherng** [comment]
https://github.com/bmewburn/vscode-intelephense/issues/1859

**Comment by fadrian06** [comment]
> It just works?
> 
> ![image](https://private-user-images.githubusercontent.com/6594915/292377466-2572ad92-0c01-453a-9c16-6f0a6871aef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjMwNjgsIm5iZiI6MTcwMzIyMjc2OCwicGF0aCI6Ii82NTk0OTE1LzI5MjM3NzQ2Ni0yNTcyYWQ5Mi0wYzAxLTQ1M2EtOWMxNi02ZjBhNjg3MWFlZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMDUyNjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzZlNTFhOTYyM2VhYjZmNGJhZWY0ZjVmN2EwMjdiODE4YzAyNjA4MTFjYWExMGE3OTY5ZjUxZDUzODJhY2NjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sh5KtfVmnmPxIWm8fc9PRmZKSPYeEIEQQN3YqiegSYE)

Yes, it works for the @deprecated tag, but it would be great if it worked for the @throws tag

**Comment by fadrian06** [comment]
> Nonetheless, if the features you requested are not there, nothing we can do here. LSP-intelephense is more of just a UI layer which shows what the serve responses. You should file a feature request to the server's repository instead. https://github.com/bmewburn/vscode-intelephense

Thanks for the almost immediate response, it is indeed a feature that they are already requesting in the vs repository Diagnostic for Uncaught Exception · Issue #1859 · bmewburn/vscode-intelephense
https://github.com/bmewburn/vscode-intelephense/issues/1859
