### ISSUE TITLE
Marking files with errors as red in the files tree?

### ISSUE THREAD

**Issue by sjns19** [sublimelsp/LSP-intelephense#97]
I'm not sure if this feature already exists and can be enabled through configuration but it would be nice if the file having errors would be marked red in the files tree, something like what VS Code does so it would be easy to track the file without having to go through each file to see where the problem lies.

From VS Code
<img width="677" alt="Screenshot 2024-02-19 at 12 20 46 PM" src="https://github.com/sublimelsp/LSP-intelephense/assets/47782595/5e05b1a5-616d-493a-a2c7-ee7b3855a93a">

Sublime
<img width="736" alt="Screenshot 2024-02-19 at 12 16 47 PM" src="https://github.com/sublimelsp/LSP-intelephense/assets/47782595/885566ae-d589-442e-9c05-1ff599ec2a69">

**Comment by jfcherng** [comment]
I don't think ST has such API.

**Comment by willrowe** [comment]
Closing this since if this is ever implemented, it would most likely be implemented in the main LSP package and not this one.
