### ISSUE TITLE
FR: add minimum lines limit to initially_folded settings 

### ISSUE THREAD

**Issue by zigi05** [sublimelsp/LSP-intelephense#98]
@jwortmann it would be awesome in my opinion if the declarations folding setting (shown below) would have an additional setting that would trigger the folding only if they're, for example, more than 5 lines. 
```
{
  "initially_folded": ["declaration"],
}
```

**Comment by jfcherng** [comment]
I am a little confused for why jwortmann is tagged. But imho this feature should be provided either the server or LSP.

**Comment by jfcherng** [comment]
Looks like you are filing an issue in a wrong repository.
